[estimator_parameters]
entry_point          = 'train.py' 
source_dir           = 'src'
instance_type        = 'ml.g5.xlarge'
instance_count       = 1 
framework_version    = '2.2'
py_version           = "py310"
base_job_name        = "lora"

use_spot_instances   = true
max_run              = 68640 # 24h * 60 min * 60 sec
max_wait             = 68640 


[hyperparameters]
tasks                = "sst2"

model-ckp            = "roberta-base"
patience             = 0 

n-train-samples      = 0 # 0 - no sampling, full dataset
n-valid-samples      = 0
n-warmup-steps       = 0 # 50
warmup-ratio         = 0.1
seed                 = 0 # 0 - no seed 
use-bf16             = 1

clf-dropout          = 0.05
hidden-dropout       = 0.20
attention-dropout    = 0.20
adam_beta1           = 0.9
adam_beta2           = 0.98

# Task specific 
sst2-epochs          = 10 
sst2-lora-config     = "all"
sst2-lora-dropout    = 0.10
sst2-batch-size      = 480 
sst2-learning-rate   = 1e-4
sst2-weight-decay    = 0.01 

cola-epochs          = 10
cola-lora-config     = "all"
cola-lora-dropout    = 0.05
cola-batch-size      = 224
cola-learning-rate   = 8.5e-4
cola-weight-decay    = 1e-9
use-gradient-checkpointing = 0

[tuner_parameters]
base_tuning_job_name = "lora-base"
objective_metric_name= "sst2_valid_acc"
objective_type       = "Maximize"
max_jobs             = 10
max_parallel_jobs    = 2
strategy             = "Bayesian"


# Metric Definitions
[[metric_definitions]]
Name = "learning_rate"
Regex = "\\'learning_rate\\': (-?[0-9\\.e-]+)"

[[metric_definitions]]
Name = "train_epoch_duration"
Regex = "Epoch duration: (-?[0-9\\.]+)s"

[[metric_definitions]]
Name = "gpu_memory"
Regex = "GPU Usage.*?\\(([0-9\\.]+)% used\\)"

[[metric_definitions]]
Name = "train_samples_sec"
Regex = "\\'train_samples_per_second\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "valid_f1"
Regex = "\\'eval_f1\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "sst2_valid_matthews_correlation"
Regex = "\\'eval_sst2_matthews_correlation\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "cola_valid_matthews_correlation"
Regex = "\\'eval_cola_matthews_correlation\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "sst2_valid_f1"
Regex = "\\'eval_sst2_f1\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "cola_valid_f1"
Regex = "\\'eval_cola_f1\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "sst2_valid_acc"
Regex = "\\'eval_sst2_accuracy\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "cola_valid_acc"
Regex = "\\'eval_cola_accuracy\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "valid_loss"
Regex = "\\'eval_loss\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "train_loss"
Regex = "\\'loss\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "epoch"
Regex = "\\'epoch\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "eval_runtime"
Regex = "\\'eval_runtime\\': (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "total_parameters"
Regex = "total_parameters: (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "learnable_parameters"
Regex = "learnable_parameters: (-?[0-9\\.]+)"

[[metric_definitions]]
Name = "model_size_mb"
Regex = "Model size: (-?[0-9\\.]+) MB"
