[tool.ruff]
ignore = ["E501"]

[tool.pyright]
reportMissingTypeStubs = false
reportMissingImports = false

[[tool.mypy]]

[[tool.mypy.overrides]]
ignore_missing_imports = true

# https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
